StudentRecruitment/Controllers/LoginController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using Recruitment.Domain.Shared.Contracts;
using Recruitment.Foundation.Common;
using Recruitment.Models.Request;
using Recruitment.Domain.Shared.Dto;
using Recruitment.Repository.Shared.Contracts;
using Newtonsoft.Json;
using Recruitment.Models.Response;

namespace Recruitment.Controllers
{
    public class LoginController : Controller
    {
        private readonly ILoginManager _loginManager;
        private readonly IUserManager _userManager;
        private readonly IStudentRepository _repor;

        public LoginController(ILoginManager loginManager, IUserManager userManager, IStudentRepository repor)
        {
            _loginManager = loginManager;
            _userManager = userManager;
            _repor = repor;
        }

        /// <summary>
        /// Landing page for Login
        /// </summary>
        /// <returns>View</returns>
        [HttpGet]
        public IActionResult UserLogin()
        {

            return View();
        }

        /// <summary>
        /// After submisssion of login form 
        /// </summary>
        /// <param name="model"></param>
        /// <returns>False if user not present or return partial view for otp if user is present</returns>
        [HttpPost]
        public IActionResult UserLogin([FromBody] LoginRequestModel model)
        {

            bool isPresent = _userManager.IsUserPresent(model.Input, model.flag); ;

            if (!isPresent)
            {
                return Json(false);

            }
            else
            {
                HttpContext.Session.SetString(Constants.Keys.LoginDetails, JsonConvert.SerializeObject(model));
                _loginManager.GenerateOtp(model.Input, model.flag);
                Guid id = _userManager.GetUserId(model.Input, model.flag);
                HttpContext.Session.SetString(Constants.Keys.Id, id.ToString());

                return PartialView(Constants.ViewNames._OtpAuthentication);
            }
        }

        /// <summary>
        /// Check whether the otp is right or not
        /// </summary>
        /// <param name="model"></param>
        /// <returns>return true if otp matches or else return false</returns>
        [HttpPost]
        public OtpVerificationResponseModel OtpAuthentication([FromBody] OtpRequestModel model)
        {
            string savedId = HttpContext.Session.GetString(Constants.Keys.Id);
            Guid userId = Guid.Parse(savedId);
            var response = _userManager.GetOtp(userId,model.Otp);

            if (response.IsVerified)
            {
                HttpContext.Session.SetString(Constants.Keys.IsLogged, Constants.Keys.Yes); 
            }
            return new OtpVerificationResponseModel()
            {
                IsVerified = response.IsVerified,
                IsExpired = response.IsExpired
            };
        }

        /// <summary>
        /// Login Page for admin
        /// </summary>
        /// <returns>Returns partial View for admin login</returns>
        [HttpGet]
        public IActionResult AdminLogin()
        {
            return PartialView(Constants.ViewNames._AdminLogin);
        }

        /// <summary>
        /// After Login Page submission
        /// </summary>
        /// <param name="model"></param>
        /// <returns>whether admin is present or not</returns>
        [HttpPost]
        public IActionResult AdminLogin([FromBody] AdminLoginRequestModel model)
        {
            AdminLoginResponseModel response = _userManager.IsAdminPresent(model.Username, model.Password);
            if (response.IsPresent == true && response.IsPasswordCorrect == true)
            {
                HttpContext.Session.SetString(Constants.Keys.IsAdminLogged, Constants.Keys.Yes);
            }
            return Json(response);
        }

        public void LoggedOut()
        {
            HttpContext.Session.SetString(Constants.Keys.IsAdminLogged, Constants.Keys.No);
            HttpContext.Session.SetString(Constants.Keys.IsLogged, Constants.Keys.No);
        }

        [HttpGet]
        public bool ResendOtp()
        {
            string email;
            var register = HttpContext.Session.GetString(Constants.Keys.Registration);
            if (register != null)
            {
                var user = JsonConvert.DeserializeObject<RegistrationRequestModel>(register);
                email = user.Email;

            }
            else
            {
                var login = HttpContext.Session.GetString(Constants.Keys.LoginDetails);
                var user = JsonConvert.DeserializeObject<LoginRequestModel>(login);
                email = user.Input;
            }
            _loginManager.GenerateOtp(email, 0);

            return true;

        }
    }
}

StudentRecruitment/Controllers/RegisterController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Recruitment.Domain.Shared.Contracts;
using Recruitment.Domain.Shared.Dto;
using Recruitment.Foundation.Common;
using Recruitment.Models;
using Recruitment.Models.Request;
using Recruitment.Models.Response;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Recruitment.Controllers
{
    public class RegisterController : Controller
    {
        private readonly ILoginManager _loginManager;
        private readonly IUserManager _userManager;
        private readonly ICourseManager _courseManager;
        private readonly ICollegeManager _collegeManager;

        public RegisterController(ILoginManager loginManager, ICourseManager courseManager, ICollegeManager collegeManager, IUserManager userManager)
        {
            _loginManager = loginManager;
            _courseManager = courseManager;
            _collegeManager = collegeManager;
            _userManager = userManager;
        }

        /// <summary>
        /// Page for Registration of users
        /// </summary>
        /// <returns>View for register page</returns>
        [HttpGet]
        public IActionResult Registration()
        {
            RegisterResponseViewModel registrationViewModel = new RegisterResponseViewModel();
            registrationViewModel.Colleges = _collegeManager.GetListedColleges(false);
            registrationViewModel.Courses = _courseManager.GetListedCourses();

            return View(registrationViewModel);
        }

        /// <summary>
        /// After submission of Register Page
        /// </summary>
        /// <param name="model"></param>
        /// <returns>return response based on whether user is already present or not</returns>
        [HttpPost]
        public IActionResult Registration([FromBody] RegistrationRequestModel model)
        {

            int flag = model.AuthenticateVia;
            var response = _userManager.IsUserPresent(model.PhoneNumber, model.Email);

            if (response)
            {
                return Json(response);
            }
            else
            {
                HttpContext.Session.SetString(Constants.Keys.Registration, JsonConvert.SerializeObject(model));
                Guid id = Guid.NewGuid();
                _userManager.SaveStudentData(model.Name, model.Password, model.PhoneNumber, model.AlternatePhoneNumber, model.CollegeId, model.CourseId, model.Email, model.RollNo, model.Semester, id);

                if (flag == 1)
                {
                    _loginManager.GenerateOtp(model.PhoneNumber, flag);
                }
                else
                {
                    _loginManager.GenerateOtp(model.Email, flag);
                }

                HttpContext.Session.SetString(Constants.Keys.Id, id.ToString());

                return PartialView(Constants.ViewNames._OtpAuthentication);
            }
        }
    }
}

StudentRecruitment/Views/Shared/_AddCollege.cshtml
@{
    Layout = null;

}
<div class="modal-body" id="addCollege">
        <div class="jumbotron">
            <h2 class="mb-2 text-center">Add College</h2>
            <div class="form-group">
                <label class="label" for="newCollegeName">College Name</label>
                <input type="text" class="form-control inputs" name="newCollegeName" id="newCollegeName">
                <small id="collegeNameError" class="d-none text-danger">This college is already present.</small>
                <small id="collegeValidation" class="d-none text-danger">Please enter a valid college name.</small>

            </div>
            <div class="form-group">
                <label for="isActive" class="control-label label">Active</label>
                <select class="form-select form-control p-0" aria-label=".form-select-sm example" id="newIsActive" name="active">
                    <option value="true" selected>Yes</option>
                    <option value="false">No</option>
                </select>
            </div>
            <div class="form-group">
                <label class="label" for="contactPerson">CutOff</label>
                <input type="number" min="0" class="form-control inputs" id="newCutoff">
                <small id="cutoffError" class="d-none text-danger">Please select a cut off.</small>
            </div>
            <div class="form-group">
                <label class="label" for="contactPerson">Contact Person</label>
                <input type="text" class="form-control inputs" id="newContactPerson">
                <small id="personError" class="d-none text-danger">Please add a contact person.</small>
            </div>
            <div class="form-group">
                <label class="label" for="contactNumber">Contact Number</label>
                <input type="text" class="form-control inputs" id="newContactNumber">
                <small id="contactError" class="d-none text-danger">Please provide a valid contact number.</small>
            </div>
            <div class="form-group">
                <label class="label" for="contactNumber">Address</label>
                <input type="text" class="form-control inputs" id="address">
                <small id="addressError" class="d-none text-danger">Please provide a address.</small>
            </div>
            <div class="form-group">
                <label class="label" for="contactNumber">State</label>
                <select class="form-select form-control p-0" aria-label=".form-select-sm example" id="state" name="state">
                    <option value="">State</option>
                    <option value="Andhra Pradesh">Andhra Pradesh</option>
                    <option value="Andaman and Nicobar Islands">Andaman and Nicobar Islands</option>
                    <option value="Arunachal Pradesh">Arunachal Pradesh</option>
                    <option value="Assam">Assam</option>
                    <option value="Bihar">Bihar</option>
                    <option value="Chandigarh">Chandigarh</option>
                    <option value="Chhattisgarh">Chhattisgarh</option>
                    <option value="Dadar and Nagar Haveli">Dadar and Nagar Haveli</option>
                    <option value="Daman and Diu">Daman and Diu</option>
                    <option value="Delhi">Delhi</option>
                    <option value="Lakshadweep">Lakshadweep</option>
                    <option value="Puducherry">Puducherry</option>
                    <option value="Goa">Goa</option>
                    <option value="Gujarat">Gujarat</option>
                    <option value="Haryana">Haryana</option>
                    <option value="Himachal Pradesh">Himachal Pradesh</option>
                    <option value="Jammu and Kashmir">Jammu and Kashmir</option>
                    <option value="Jharkhand">Jharkhand</option>
                    <option value="Karnataka">Karnataka</option>
                    <option value="Kerala">Kerala</option>
                    <option value="Madhya Pradesh">Madhya Pradesh</option>
                    <option value="Maharashtra">Maharashtra</option>
                    <option value="Manipur">Manipur</option>
                    <option value="Meghalaya">Meghalaya</option>
                    <option value="Mizoram">Mizoram</option>
                    <option value="Nagaland">Nagaland</option>
                    <option value="Odisha">Odisha</option>
                    <option value="Punjab">Punjab</option>
                    <option value="Rajasthan">Rajasthan</option>
                    <option value="Sikkim">Sikkim</option>
                    <option value="Tamil Nadu">Tamil Nadu</option>
                    <option value="Telangana">Telangana</option>
                    <option value="Tripura">Tripura</option>
                    <option value="Uttar Pradesh">Uttar Pradesh</option>
                    <option value="Uttarakhand">Uttarakhand</option>
                    <option value="West Bengal">West Bengal</option>
                </select>
                <small id="stateError" class="d-none text-danger">Please select a state.</small>
            </div>
            <div class="d-flex justify-content-end">
                <button type="button" class="btnn btnn-outline-info mr-2" data-dismiss="modal" id="collegeClose">Close</button>
                <button type="button" class="btnn btnn-info" id="addCollegeSubmit">Add</button>
            </div>
        </div>
</div>

StudentRecruitment/Views/Shared/_AptitudeQuestionAdd.cshtml
@{
    Layout = null;
    @model List<Recruitment.Domain.Shared.Dto.TestSectionResponseModel>;

}
<div class="modal-body" id="addModal">
    <form>
        <div class="jumbotron">
            <h2 class="mb-2 text-center">Add Question</h2>
            <div class="form-group">
                <label class="label" for="questionContent">Question</label>
                <input type="text" class="form-control inputs" id="questionContent" placeholder="Enter Question" name="questionContent" required>
                <small class="text-danger d-none" id="aptitudeNewQuestionError">Please enter valid question</small>
            </div>
            <div class="form-group" id="optionDiv">
                @*<label class="label">Option: <i class="fas fa-plus-circle" id="addOptionBtn"></i> Add Option</label>*@
                <label class="label">Option:</label> <button type="button" class="btn shadow-none" id="addOptionBtn"><i class="fas fa-plus-circle"></i>Add Option</button>
                <small class="text-danger d-none" id="aptitudeNewQuestionOptionError">Please choose a option</small>


            </div>
            <div class="d-flex justify-content-end">
                <button type="button" class="btnn btnn-outline-info mr-2" data-dismiss="modal">Close</button>
                <button type="button" class="btnn btnn-info  saveModal" id="addSubmit">ADD</button>
            </div>
        </div>
    </form>
</div>

StudentRecruitment/Views/Shared/_AptitudeTestReport.cshtml
@{
    Layout = null;
    @model List<Recruitment.Domain.Shared.Dto.AptitudeAttemptedQuestionResponseModel>;
}
<div id="aptitudeInfo">
    <div class="summary card mb-3 mt-3">
        <div class="card-body">
            <h4 class="text-left">Marks Obtained</h4>
            <p class="numbers">
                @for (var m = 0; m < Model.Count; m++)
                {
                    <span class="mr-3">@Model[m].SectionName:@Model[m].SectionMarks/@Model[m].SectionTotalMarks</span>
                }
            </p>
        </div>
    </div>
    @for(var sec = 0; sec < Model.Count; sec++)
     {
        <div class="mt-2 mb-1 aptiSection">
            <div class="d-flex align-items-center">
                <button type="button" class="collapsible">@Model[sec].SectionName</button>
                <i class="fas fa-chevron-up fa-lg shrink rotate" data-toggle="collapse" data-target="#@Model[sec].TrimmedSectionName"></i>
            </div>
            <div class="content collapse show" id="@Model[sec].TrimmedSectionName">
                @for (var q = 0; q < Model[sec].Section.Count; q++)
                {
                    <div class="mb-2 questionDiv">
                        <p class="aptiQuestions"> <span class="questionNumber">@(q + 1)</span> @Model[sec].Section[q].QuestionContent</p>
                        <input type="hidden" class="questionId" value="@Model[sec].Section[q].QuestionId" />
                        @for (int i = 0; i < Model[sec].Section[q].Options.Count; i++)
                        {
                            if (Model[sec].Section[q].UserOptionId != null)
                            {

                                if (Model[sec].Section[q].UserOptionId == Model[sec].Section[q].Options[i].OptionId && Model[sec].Section[q].Options[i].IsTrue == true)
                                {
                                    <div><label class="optLabels " value="@Model[sec].Section[q].Options[i].OptionId"><i class="far fa-check-circle correct"></i> @Model[sec].Section[q].Options[i].Option </label></div>
                                }
                                else
                                {
                                    if (Model[sec].Section[q].Options[i].IsTrue == true)
                                    {
                                        <div><label class="optLabels" value="@Model[sec].Section[q].Options[i].OptionId"><i class="far fa-check-circle correct"></i> @Model[sec].Section[q].Options[i].Option </label></div>

                                    }
                                    else if (Model[sec].Section[q].UserOptionId == Model[sec].Section[q].Options[i].OptionId)
                                    {
                                        <div><label class="optLabels" value="@Model[sec].Section[q].Options[i].OptionId"><i class="far fa-times-circle wrong"></i> @Model[sec].Section[q].Options[i].Option </label></div>
                                    }

                                    else
                                    {
                                        <div><label class="optLabels margedLabel" value="@Model[sec].Section[q].Options[i].OptionId"> @Model[sec].Section[q].Options[i].Option </label></div>

                                    }
                                }
                            }
                            else
                            {
                                <div><label class="optLabels margedLabel" value="@Model[sec].Section[q].Options[i].OptionId"> @Model[sec].Section[q].Options[i].Option </label></div>
                            }

                        }
                    </div>
                }
            </div>
        </div>
     }
</div>

StudentRecruitment/Views/Shared/_CodingQuestionAdd.cshtml
@{
    Layout = null;

}
<div class="modal-body" id="addModal">
    <form>
        <div class="jumbotron">
            <h2 class="mb-2 text-center">Add Question</h2>
            <div class="form-group">
                <label class="label" for="questionContent">Question</label>
                <input type="text" class="form-control inputs" id="questionContent" placeholder="Enter Your Question" name="questionContent" required>
                <small class="text-danger d-none" id="codingNewQuestionError">Please enter valid question</small>
            </div>
            <div class="form-group">
                <label class="label" for="questionMarks">Marks</label>
                <input type="number" class="form-control inputs" id="questionMarks" placeholder="Enter Marks" name="questionMarks" required>
                <small class="text-danger d-none" id="codingNewMarksError">Please enter valid marks</small>
            </div>
            <div class="d-flex justify-content-end align-content-center">
                <button type="button" class="btnn btnn-outline-info mr-2 " data-dismiss="modal">Close</button>
                <button type="button" class="btnn btnn-info  saveModal" id="addCodingSubmit">ADD</button>
            </div>
        </div>
    </form>
</div>

StudentRecruitment/Views/Shared/_CodingQuestionEdit.cshtml
@{
    Layout = null;
    @model Recruitment.Domain.Shared.Dto.CodingQuestionInfo
}
<div class="modal-body" id="editModal">
    <form>
        <div class="jumbotron">
            <h2 class="mb-2 text-center">Edit Question</h2>
            <div class="form-group">
                <input type="hidden" value="@Model.QuestionId" id="questionId" />
                <label class="label" for="newQuestionContent">Question</label>
                <input type="text" class="form-control inputs" id="newQuestionContent" name="newQuestionContent" value="@Model.QuestionContent" required>
                <small class="text-danger d-none" id="codingQuestionEditError">Please enter valid question</small>
            </div>
            <div class="form-group">
                <label for="isActive" class="control-label label">Active</label>
                <select class="form-select form-control p-0" aria-label=".form-select-sm example" id="isActive" name="section">
                    @if (Model.IsActive == true)
                    {
                        <option value="true" selected>Yes</option>
                        <option value="false">No</option>
                    }
                    else
                    {
                        <option value="true">Yes</option>
                        <option value="false" selected>No</option>
                    }

                </select>
            </div>
            <div class="form-group">
                <label class="label" for="questionContent">Marks</label>
                <input type="number" class="form-control inputs" id="questionMarks" name="questionMarks" value="@Model.QuestionMarks" required>
                <small class="text-danger d-none" id="codingMarksError">Please enter valid marks</small>
            </div>
            <div class="d-flex justify-content-end align-content-center">
                <button type="button" class="btnn btnn-outline-info mr-2" data-dismiss="modal">Close</button>
                <button type="button" class="btnn btnn-info  saveModal" id="editCodingSubmit">Save Changes</button>

            </div>
        </div>
    </form>
</div>

StudentRecruitment/Views/Shared/_CodingSection.cshtml
@{
    Layout = null;
}
@model Recruitment.Models.Response.CodingQuestionsResponseModel
<div id="codingSection">
    <div id="codingQuestionSection">
        <input type="hidden" id="questionId" asp-for="@Model.QuestionId" value="@Model.CodingQuestion.QuestionId" />
        <textarea readonly class="w-100 h-100" id="codingQuestion">@Html.Raw(@Model.CodingQuestion.QuestionContent)</textarea>
    </div>
    <div id="userCodeSection">
        <textarea name="userCode" class="w-100 h-100" id="userCode" placeholder="Write your code here">@Model.CodingQuestion.CodeSubmitted </textarea>
    </div>
     
</div>

StudentRecruitment/Views/Shared/_CollegeEdit.cshtml
@{
    Layout = null;
    @model Recruitment.Domain.Shared.Dto.CollegeInfoResponseModel;
    string[] state = new string[] {"Andhra Pradesh",
                 "Arunachal Pradesh",
                 "Assam",
                 "Bihar",
                 "Chhattisgarh",
                 "Goa",
                 "Gujarat",
                 "Haryana",
                 "Himachal Pradesh",
                 "Jammu and Kashmir",
                 "Jharkhand",
                 "Karnataka",
                 "Kerala",
                 "Madhya Pradesh",
                 "Maharashtra",
                 "Manipur",
                 "Meghalaya",
                 "Mizoram",
                 "Nagaland",
                 "Odisha",
                 "Punjab",
                 "Rajasthan",
                 "Sikkim",
                 "Tamil Nadu",
                 "Telangana",
                 "Tripura",
                 "Uttarakhand",
                 "Uttar Pradesh",
                 "West Bengal",
                 "Andaman and Nicobar Islands",
                 "Chandigarh",
                 "Dadra and Nagar Haveli",
                 "Daman and Diu",
                 "Delhi",
                 "Lakshadweep",
                 "Puducherry" };
}
<div class="modal-body" id="editCollege">
    <form>
        <div class="jumbotron">
            <h2 class="mb-2 text-center">Edit College</h2>
            <div class="form-group">
                <input type="hidden" value="@Model.Id" id="collegeId" />
                <label class="label" for="collegeName">College Name</label>
                <input type="text" class="form-control inputs" name="collegeName" value="@Model.Name" id="editedCollegeName" required>
                <small class="text-danger d-none" id="editedCollegeNameError">Please provide valid college name</small>
                <small class="text-danger d-none" id="existError">College name already exist</small>
            </div>
            <div class="form-group">
                <label for="isActive" class="control-label label">Active</label>
                <select class="form-select form-control p-0" aria-label=".form-select-sm example" id="editedIsActive" name="section">
                    @if (Model.IsActive == true)
                    {
                        <option value="true" selected>Yes</option>
                        <option value="false">No</option>
                    }
                    else
                    {
                        <option value="true">Yes</option>
                        <option value="false" selected>No</option>
                    }

                </select>
            </div>
            <div class="form-group">
                <label class="label" for="contactPerson">CutOff</label>
                <input type="number" min="0" class="form-control inputs" id="editedCutoff" value="@Model.Cutoff" required>
            </div>
            <div class="form-group">
                <label class="label" for="contactPerson">Contact Person</label>
                <input type="text" class="form-control inputs" id="editedContactPerson" value="@Model.ContactPerson" required>
                <small class="text-danger d-none" id="editedContactPersonError">Please enter valid name</small>
            </div>
            <div class="form-group">
                <label class="label" for="contactNumber">Contact Number</label>
                <input type="text" class="form-control inputs" id="editedContactNumber" value="@Model.ContactPersonNumber" required>
                <small class="text-danger d-none" id="editedContactError">Please enter valid name</small>
            </div>
            <div class="form-group">
                <label class="label" for="contactNumber">Address</label>
                <input type="text" class="form-control inputs" value="@Model.Address" id="editedAddress">
                <small id="editedAddressError" class="d-none text-danger">Please provide a address.</small>
            </div>
            <div class="form-group">
                <label class="label" for="contactNumber">State</label>
                <select class="form-select form-control p-0" aria-label=".form-select-sm example" id="editedState" name="state">
                    @foreach (var st in state)
                    {
                        if (st == Model.State)
                        {
                            <option value=@st selected>@st</option>
                        }
                        else
                        {
                            <option value=@st>@st</option>
                        }
                    }
                </select>
                <small id="editedStateError" class="d-none text-danger">Please select a state.</small>
            </div>
            <div class="d-flex justify-content-end">
                <button type="button" class="btnn btnn-outline-info mr-2" data-dismiss="modal">Close</button>
                <button type="button" class="btnn btnn-info  saveModal" id="editCollegeSubmit">Save Changes</button>

            </div>
        </div>
    </form>
</div>

StudentRecruitment/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600&family=Roboto:wght@100;300;400;500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel=" stylesheet" href="~/css/Login/UserLogin.css" />
    <link rel="stylesheet" href="~/css/Login/OtpAuthentication.css" />
    <link rel="stylesheet" href="~/css/Register/Registration.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/ajax/jquery.unobtrusive-ajax.js"></script>

</head>
<body id="loginBody">
    <header id="site-header" class="fixed-top">
        <nav class="navbar navbar-expand-lg" id="myNavbar">
            <div class="container-fluid">
                <a class="navbar-brand" href="#"><img src="~/Images/GC-Logo.png" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
                        <li>
                            <a class="gs-headermenu__link btnn btnn-outline-info px-5 px-xl-4 mr-3 btnlink" aria-current="page" id="registerButton" asp-controller="Register" asp-action="Registration">Sign Up</a>
                        </li>
                        <li>
                            <a class="gs-headermenu__link btnn btnn-info px-5 px-xl-4 btnlink" aria-current="page" id="adminLogin">Admin</a>
                        </li>
                        <li>
                            <a class="gs-headermenu__link btnn btnn-outline-info px-5 px-xl-4 mr-3 d-none btnlink" aria-current="page" asp-controller="Login" asp-action="UserLogin" id="loginButton">Sign In</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

    </header>
    <div id="viewLoader">
        @RenderBody()
    </div>
</body>
</html>

StudentRecruitment/Views/Shared/_NotQualified.cshtml
@{
    ViewData["title"] = "Not Qualified";
    Layout = null;
}
<div class="container">
    <p class="mt-3 text-danger text-center">Unfortunately, you could not qualify for the next round.</p>
</div>